# Generated by Django 2.1.2 on 2018-10-31 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_auto_20181031_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategorias',
            new_name='SubCategoria',
        ),
    ]
