# Generated by Django 2.1.2 on 2018-11-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_auto_20180926_2250'),
        ('catalogos', '0004_auto_20181031_2036'),
    ]

    operations = [
    ]
