# Generated by Django 2.1.2 on 2018-11-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadet',
            name='creado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='creado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
